# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
dw_pandas = pd.read_csv(url)
display(dw_pandas)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Headers are not in snake_case
#All categories have null values and DataFrame has unecessary empty rows

customer_id = dw_pandas['Customer']
state = dw_pandas['ST']
gender = dw_pandas['GENDER']
education = dw_pandas['Education']
customer_lifetime_value = dw_pandas['Customer Lifetime Value'] #Customer Lifetime Value should be an "int64" or "float64" not and "object"
income = dw_pandas['Income']
monthly_premium_auto = dw_pandas['Monthly Premium Auto']
number_of_open_complaints = dw_pandas['Number of Open Complaints'] # Number of complaints are dates "object" instead of an "int64"
policy_type = dw_pandas['Policy Type']
vehicle_class = dw_pandas['Vehicle Class'] # Vehicle class mixed with number of doors
total_claim_amount = dw_pandas['Total Claim Amount']

display(customer_id)
display(state)
display(gender)
display(education)
display(customer_lifetime_value)
display(income)
display(monthly_premium_auto)
display(number_of_open_complaints)
display(policy_type)
display(vehicle_class)
display(total_claim_amount)

0       RB50392
1       QZ44356
2       AI49188
3       WW63253
4       GA49547
         ...
4003        NaN
4004        NaN
4005        NaN
4006        NaN
4007        NaN
Name: Customer, Length: 4008, dtype: str

0       Washington
1          Arizona
2           Nevada
3       California
4       Washington
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: ST, Length: 4008, dtype: str

0       NaN
1         F
2         F
3         M
4         M
       ...
4003    NaN
4004    NaN
4005    NaN
4006    NaN
4007    NaN
Name: GENDER, Length: 4008, dtype: str

0                     Master
1                   Bachelor
2                   Bachelor
3                   Bachelor
4       High School or Below
                ...
4003                     NaN
4004                     NaN
4005                     NaN
4006                     NaN
4007                     NaN
Name: Education, Length: 4008, dtype: str

0               NaN
1        697953.59%
2       1288743.17%
3        764586.18%
4        536307.65%
           ...
4003            NaN
4004            NaN
4005            NaN
4006            NaN
4007            NaN
Name: Customer Lifetime Value, Length: 4008, dtype: str

0           0.0
1           0.0
2       48767.0
3           0.0
4       36357.0
         ...
4003        NaN
4004        NaN
4005        NaN
4006        NaN
4007        NaN
Name: Income, Length: 4008, dtype: float64

0       1000.0
1         94.0
2        108.0
3        106.0
4         68.0
         ...
4003       NaN
4004       NaN
4005       NaN
4006       NaN
4007       NaN
Name: Monthly Premium Auto, Length: 4008, dtype: float64

0       1/0/00
1       1/0/00
2       1/0/00
3       1/0/00
4       1/0/00
         ...
4003       NaN
4004       NaN
4005       NaN
4006       NaN
4007       NaN
Name: Number of Open Complaints, Length: 4008, dtype: str

0        Personal Auto
1        Personal Auto
2        Personal Auto
3       Corporate Auto
4        Personal Auto
             ...
4003               NaN
4004               NaN
4005               NaN
4006               NaN
4007               NaN
Name: Policy Type, Length: 4008, dtype: str

0       Four-Door Car
1       Four-Door Car
2        Two-Door Car
3                 SUV
4       Four-Door Car
            ...
4003              NaN
4004              NaN
4005              NaN
4006              NaN
4007              NaN
Name: Vehicle Class, Length: 4008, dtype: str

0          2.704934
1       1131.464935
2        566.472247
3        529.881344
4         17.269323
           ...
4003            NaN
4004            NaN
4005            NaN
4006            NaN
4007            NaN
Name: Total Claim Amount, Length: 4008, dtype: float64

In [ ]:
print("Number of Unique Values\n")
print("Customer Ids:")
display((customer_id).nunique())
print("State:")
display((state).nunique())
print("Gender:")
display((gender).nunique())
print("Education:")
display((education).nunique())
print("Customer Lifetime Value:")
display((customer_lifetime_value).nunique())
print("Income:")
display((income).nunique())
print("Monthly Premium Auto:")
display((monthly_premium_auto).nunique())
print("Open Complaints:")
display((number_of_open_complaints).nunique())
print("Policy type:")
display((policy_type).nunique())
print("Vehicle Class:")
display((vehicle_class).nunique())
print("Total Claim Amount:")
display((total_claim_amount).nunique())
print("\n")

print("Categorical Values")

print("Unique State")
display((state).unique())
print("Unique Gender")
display((gender).unique())
print("Unique Education")
display((education).unique())
print("Unique Policy")
display((policy_type).unique())
print("Unique Class")
display((vehicle_class).unique())
print("\n")
#Categorical values have different formats such as the State, Gender and Unique Class

print("Total Numerical Values\n")
print("Customer Ids:")
display((customer_id).value_counts().sum())
print("Monthly Premium Auto:")
display((monthly_premium_auto).value_counts().sum())
print("Customer Lifetime Value:")
display((customer_lifetime_value).value_counts().sum())
print("Income:")
display((income).value_counts().sum())
print("Open Complaints:")
display((number_of_open_complaints).value_counts().sum())
print("Total Claim Amount:")
display((total_claim_amount).value_counts().sum())
#3 Missing or Null values for the Customer Lifetime Value column

In [ ]:
# This is to calculate mean, mode and median for numerical values

print("\nTotal Numerical Values Mean\n")

print("\nIncome:")
display((income).mean())
print("\nMonthly Premium Auto:")
display((monthly_premium_auto).mean())
print("\nTotal Claim Amount:")
display((total_claim_amount).mean())
print("\n")

print("\nTotal Numerical Values Mode\n")

print("\nIncome:")
display((income).mode())
print("\nMonthly Premium Auto:")
display((monthly_premium_auto).mode())
print("\nTotal Claim Amount:")
display((total_claim_amount).mode())
print("\n")

print("\nTotal Numerical Values Median\n")

print("\nIncome:")
display((income).median())
print("\nMonthly Premium Auto:")
display((monthly_premium_auto).median())
print("\nTotal Claim Amount:")
display((total_claim_amount).median())
print("\n")

print("\nTotal Numerical Values Standard Deviation\n")

print("\nIncome:")
display((income).std())
print("\nMonthly Premium Auto:")
display((monthly_premium_auto).std())
print("\nTotal Claim Amount:")
display((total_claim_amount).std())
print("\n")

print("\nTotal Numerical Values Quantile\n")

print("\nIncome:")
display((income).quantile(0.50))
print("\nMonthly Premium Auto:")
display((monthly_premium_auto).quantile(0.50))
print("\nTotal Claim Amount:")
display((total_claim_amount).quantile(0.50))
print("\n")

dw_pandas.describe()

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [ ]:
#Filters the bottom 5 states with the least amount of customers

less_common_locations = state.value_counts(ascending=True).tail() # Value counts for the number of customers, ascending = True for ascending order and .tail() to give us the bottom 5 states
display(less_common_locations)

ST
Nevada         98
Cali          120
Arizona       186
California    211
Oregon        320
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [ ]:
# Counts the total policis sold for each type
policies_count = policy_type.value_counts()
display(policies_count)

# Gives us the name of the top policy sold
top_policy_sold = policies_count.idxmax()
display(top_policy_sold)

# The maximum number of top policy sold
top_policy_sold = policies_count.max()
display(top_policy_sold)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

'Personal Auto'

np.int64(780)

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [ ]:
income_personal_auto = dw_pandas.loc[policy_type == "Personal Auto"] # This will show all the customers with Personal Auto 
display(income_personal_auto)
income_corporate_auto = dw_pandas.loc[policy_type == "Corporate Auto"] # This will show all the customers with Corporate Auto
display(income_corporate_auto)

average_income_personal_auto = income_personal_auto["Income"].mean()
display(average_income_personal_auto)
average_income_corporate_auto = income_corporate_auto["Income"].mean()
display(average_income_corporate_auto)

# The average income for customers with the Personal Auto (38180.6) is lower than the customers with Corporate (41390.3)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
...,...,...,...,...,...,...,...,...,...,...,...
1065,XD85577,Cali,M,Bachelor,284226.69%,69417.0,73.0,1/1/00,Personal Auto,Four-Door Car,30.874869
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1/1/00,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,1/2/00,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
...,...,...,...,...,...,...,...,...,...,...,...
1045,WZ31900,Oregon,F,Bachelor,864970.06%,94389.0,107.0,1/0/00,Corporate Auto,SUV,85.063708
1050,BJ53923,Arizona,M,High School or Below,260027.21%,51978.0,66.0,1/0/00,Corporate Auto,Four-Door Car,144.782152
1052,FB23788,Oregon,M,High School or Below,882883.50%,86721.0,111.0,1/0/00,Corporate Auto,SUV,532.800000
1056,PI47776,Oregon,F,Bachelor,253070.51%,89451.0,63.0,1/0/00,Corporate Auto,Four-Door Car,61.769564
1059,YG44474,Oregon,M,College,1401472.13%,54193.0,117.0,1/0/00,Corporate Auto,SUV,720.752945

np.float64(38180.69871794872)

np.float64(41390.31196581197)

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [57]:
threshold_25_quantile = total_claim_amount.quantile(0.25)
threshold_75_quantile = total_claim_amount.quantile(0.75)
display(threshold_25_quantile)
display(threshold_75_quantile)

top_total_claim_amount_customers = dw_pandas[total_claim_amount > threshold_75_quantile] #Customers with total claim amount greater than 75 of the total group
display(top_total_claim_amount_customers)

bottom_total_claim_amount_customers = dw_pandas[total_claim_amount < threshold_25_quantile] #Customers with total claim amount less than 25 of the total group
display(bottom_total_claim_amount_customers)

# We can see that the 75 quantile customers have a higher education level, customer lifetime value, monthly premium auto and income
top_total_claim_amount_customers.describe()

np.float64(202.157702)

np.float64(532.8)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
17,OE15005,Cali,NaN,College,394524.16%,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
23,TZ98966,Nevada,NaN,Bachelor,245019.10%,0.0,73.0,1/3/00,Corporate Auto,Four-Door Car,554.376763
26,US89481,California,NaN,Bachelor,394637.21%,0.0,111.0,1/0/00,Personal Auto,Four-Door Car,799.200000
...,...,...,...,...,...,...,...,...,...,...,...
1059,YG44474,Oregon,M,College,1401472.13%,54193.0,117.0,1/0/00,Corporate Auto,SUV,720.752945
1061,RY92647,Cali,F,Bachelor,1050677.17%,0.0,92.0,1/0/00,Personal Auto,Four-Door Car,546.524896
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11%,79487.0,114.0,1/0/00,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
15,BW63560,Oregon,NaN,Bachelor,746313.94%,24599.0,64.0,1/1/00,Corporate Auto,Four-Door Car,42.920271
21,QK46697,Washington,M,Bachelors,617710.93%,61040.0,79.0,1/1/00,Personal Auto,Two-Door Car,20.382876
...,...,...,...,...,...,...,...,...,...,...,...
1050,BJ53923,Arizona,M,High School or Below,260027.21%,51978.0,66.0,1/0/00,Corporate Auto,Four-Door Car,144.782152
1051,CZ96653,Oregon,F,Bachelor,853479.28%,47325.0,107.0,1/0/00,Personal Auto,SUV,64.598216
1056,PI47776,Oregon,F,Bachelor,253070.51%,89451.0,63.0,1/0/00,Corporate Auto,Four-Door Car,61.769564
1063,GQ66762,Cali,M,College,477368.64%,33701.0,63.0,1/0/00,Personal Auto,Four-Door Car,171.325856
1065,XD85577,Cali,M,Bachelor,284226.69%,69417.0,73.0,1/1/00,Personal Auto,Four-Door Car,30.874869

             Income  Monthly Premium Auto  Total Claim Amount
count    264.000000            264.000000          264.000000
mean   23677.344697            165.193182          782.228263
std    27013.483721            623.930992          292.751640
min        0.000000             63.000000          537.600000
25%        0.000000             99.000000          606.521741
50%    18807.000000            114.000000          679.597985
75%    42423.750000            133.250000          851.400000
max    99316.000000          10202.000000         2893.239678